### ISSUE TITLE
Need to be retrained?

### ISSUE THREAD

**Issue by annmusic** [dafei-qin/NFR_pytorch#1]
i have own source and target face mesh, if i want to transfer animations from source mesh to target mesh, whether the NFR needs to be retrained?

**Comment by dafei-qin** [comment]
Hi there, thanks for your interest of our work.

The network DONT need to be retrained. Currently, you can transfer expressions from provided sources to your target mesh.
For the target mesh some standardization process may be required.  

Later we will release the code that can help you pre-process your own source mesh so that you can transfer your own expression to any target meshes.
